#!/bin/zsh

if [ -z "$1" ]; then
    Usqueue
elif [ -z "$2" ]; then
    displayLines=$1
    linesShown=$(( $displayLines + 3 ))
    Usqueue | head -n "$linesShown"
else
    refreshTime=$1
    displayLines=$2
    headerSize=3 # Full height of the header part of Usqeue
    fullEscape=0
    numOnQueue=$(( $(Usqueue | wc -l) - headerSize ))
    infoLines=(" ") # First entry is a blank line to create buffer between Usqueue and infoLines
    infoLines+=("# of uncompleted jobs: $numOnQueue")
    removeUnwantedLine=${#infoLines[@]}
    infoLines+=($'\033[1;33mNOTE\033[0m: Press q or Q to exit.')
    numInfoLines=${#infoLines[@]}
    if (( numOnQueue > 0 )); then
        linesShown=$(( displayLines + headerSize ))
        isFirst=1
        while (( numOnQueue > 0 )); do
            if (( isFirst )); then
                isFirst=0
            else
                __clear_lines "$(( linesShown + numInfoLines ))"
                infoLines[$removeUnwantedLine]="# of uncompleted jobs: $numOnQueue"
            fi
            if (( linesShown > numOnQueue )); then
                linesShown=$(( numOnQueue + headerSize ))
            fi
            Usqueue | head -n "$linesShown"
            printf '%s\n' "${infoLines[@]}"
            printf '%s' "Input: "
            fullEscape=$(__wait_for_keypress $refreshTime)
            $fullEscape && break 
            numOnQueue=$(( $(Usqueue | wc -l) - headerSize ))
            while (( numOnQueue < 0 )); do
                quickTime=0.05
                fullEscape=$(__wait_for_keypress $quickTime)
                $fullEscape && break
                numOnQueue=$(( $(Usqueue | wc -l) - headerSize ))
            done
            $fullEscape && break
        done
    else
        emptyJobs=$'\033[1;33mWarning:\033[0m There are no jobs running on Unity right now. Either your script hasn\'t finished submitting them, they\'ve completed already, or you forgot to submit any.'
    fi

    if $fullEscape; then
        # Do Nothing
    else
        timer=17
        numRings=3
        spacingSecs=1.275
        btwnRings=0.875
        if [[ ! -z $emptyJobs ]]; then
            printf '%s' "$emptyJobs"
        else
            __clear_lines "$(( linesShown + numInfoLines ))"
            finalOutput=$'All jobs have either \033[1;32mfinished\033[0m running on Unity, have \033[1;31mfailed\033[0m to be picked up by Slurm, or were \033[1;31m aborted\033[0m in their execution due to errors. Check your various outfile directories for details.'
            cols=$(tput cols)
            wrappedLines=$(echo "$finalOutput" | fold -s -w $cols)
            echo "$wrappedLines" | while IFS= read -r line; do
                printf '%s\n' "$line"
            done 
        fi 
        unset "infoLines[$removeUnwantedLine]"
        printf '%s\n' "${infoLines[@]}"
        printf '%s' "Input: "
        while (( timer > 0 )); do
            for i in {1..$numRings}; do
                printf "\a"
                shouldBreak=$(__wait_for_keypress $spacingSecs)
                $shouldBreak && break
            done
            $shouldBreak && break
            shouldBreak=$(__wait_for_keypress $btwnRings)
            $shouldBreak && break
            (( timer-- ))
        done
    fi
fi
